const movie = "M18,9H16V7H18M18,13H16V11H18M18,17H16V15H18M8,9H6V7H8M8,13H6V11H8M8,17H6V15H8M18,3V5H16V3H8V5H6V3H4V21H6V19H8V21H16V19H18V21H20V3H18Z"
const sound = "M12,2A3,3 0 0,1 15,5V11A3,3 0 0,1 12,14A3,3 0 0,1 9,11V5A3,3 0 0,1 12,2M19,11C19,14.53 16.39,17.44 13,17.93V21H11V17.93C7.61,17.44 5,14.53 5,11H7A5,5 0 0,0 12,16A5,5 0 0,0 17,11H19Z"
const photo = "M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"

export const PROJECTS = [
  {
    date: 2018,
    icon: movie,
    title: '"En la tardor de la història" (Curtmetratge)',
    subtitle: '4k',
    role: 'Com a Director (Postproducció) Protagonitzat per Enric Majó i Àlex Casanovas',
  },
  {
    date: 2017,
    icon: movie,
    title: '"Fatarella 1938: Ofensiva republicana" (Curtmetratge documental)',
    subtitle: 'HD',
    role: 'Com a Director (Postproducció)',
  },
  {
    date: 2017,
    icon: movie,
    title: '"La herencia de Martí" (Curtmetratge)',
    subtitle: 'AVED. 4K',
    role: 'Com a Director (Postproducció)',
  },
  {
    date: 2014,
    icon: movie,
    title: 'Talleu',
    subtitle: 'Dirigit per Josep Oller. Bande à part. HD',
    role: 'Com a Ajudant de Direcció',
  },
  {
    date: 2014,
    icon: movie,
    title: 'Nada en común',
    subtitle: 'Dirigit per Josep Oller. Bande à part. HD',
    role: 'Com a Ajudant de Direcció',
  },
  {
    date: 2014,
    icon: movie,
    title: 'Versió tercera',
    subtitle: 'Dirigit per Josep Oller. Bande à part. HD.',
    role: 'Al Departament de Producció (Ajudant de Producció)',
  },
  {
    date: 2012,
    icon: movie,
    title: '"Stop Alzheimer" (spot)',
    subtitle: 'Dirigit per Judith Mora. AVED. HD',
    role: 'Al Departament de Producció (Cap de Producció)',
  },
  {
    date: 2012,
    icon: photo,
    title: '"The Jump! WTF experience" (llargmetratge documental)',
    subtitle: 'Dirigit per Carme Puche. Operador de càmera (segona unitat) Estudi Puche Expressions i AVED. HD.',
    role: 'Al Departament de Fotografia',
  },
  {
    date: 2012,
    icon: photo,
    title: 'Festival Engresca\'t 2012. (reportatge).',
    subtitle: 'Operador de càmera. AVED. HD.',
    role: 'Al Departament de Fotografia',
  },
  {
    date: 2011,
    icon: movie,
    title: '"Un balcó d\'Abril" (Curtmetratge)',
    subtitle: 'ECIB i AVED. HD',
    role: 'Com a Director',
  },
  {
    date: 2011,
    icon: sound,
    title: 'La última habitación',
    subtitle: 'Dirigit per Pilar M. Aláez. ECIB i AVED. HD.',
    role: 'Al Departament de So',
  },
  {
    date: 2011,
    icon: movie,
    title: 'Supermarket Inn',
    subtitle: 'Dirigit per Sara López. ECIB. 35mm.',
    role: 'Al Departament de Producció (Ajudant de producció) Guanyador a "millor curtmetratge de ficció" en el Eurofilm festival.',
  },
  {
    date: 2011,
    icon: movie,
    title: 'Dead body',
    subtitle: 'dirigit per Aitor de Haro. ECIB. HD.',
    role: 'Al Departament de Producció (Ajudant de Producció) Seleccionat a la categoria de "Nova autoria" en el Festival de Cinema de Sitges.',
  },
  {
    date: 2011,
    icon: sound,
    title: 'Lo que siempre te quise decir',
    subtitle: 'Dirigit per Àngel Miñana. ECIB. HD.',
    role: 'Al Departament de So',
  },
  {
    date: 2010,
    icon: movie,
    title: 'Hibris',
    subtitle: 'Dirigit per Alex Izman. ECIB. 16mm',
    role: 'Com a Ajudant de Direcció',
  },
  {
    date: 2010,
    icon: sound,
    title: '18.04',
    subtitle: 'Dirigit per Laura Abelló. ECIB. HD.',
    role: 'Al Departament de So',
  },
  {
    date: 2009,
    icon: movie,
    title: '"La basarda". (Curtmetratge)',
    subtitle: 'ECIB. HD Seleccionat a la secció "Encuentro audivisual de jóvenes" al Festival Internacional de Cinema de Valencia',
    role: 'Com a Director',
  },
  {
    date: 2009,
    icon: photo,
    title: '"Trips" (curtmetratge)',
    subtitle: 'Dirigit per Jaume Molera i Joan Llaneras. Operador de càmera. ECIB. HD.',
    role: 'Al Departament de Fotografia',
  },
  {
    date: 2009,
    icon: photo,
    title: 'Lark About. "Camp a través". (videoclip)',
    subtitle: 'Dirigit per Àngel Miñana. Ajudant de fotografia. ECIB. HD',
    role: 'Al Departament de Fotografia',
  },
  {
    date: 2008,
    icon: movie,
    title: '"Poema Antic" (Curtmetratge)',
    subtitle: 'ECIB. Super8mm/ Digital',
    role: 'Com a Director',
  },
]